backend:
  name: github
  repo: kaumarmintini/psicologakauanymarmintini-site
  branch: main

  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Textos"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
